services:

  api:
    build: .
    container_name: todo_api
    ports:
      - "8000:8000"
      - "7860:7860"
    depends_on:
      - postgres
    environment:
      DATABASE_URL: postgresql://postgres:postgres@postgres:5432/todo_db
      API_URL: http://api:8000/api/v1/todos/todos
    restart: always

  postgres:
    image: postgres:15
    container_name: todo_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: todo_db
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always

volumes:
  postgres_data: